version: '2'

services:
    memcached:
        image: memcached:alpine
    php:
        build: docker/php5.6-fpm
        links:
            - memcached
        volumes:
            - ./capella:/var/www/capella
    nginx:
        build: docker/nginx
        ports:
            - 8081:80
        links:
            - php
            - memcached
        volumes_from:
            - php
