version: '2'

services:
    memcached:
        image: memcached:alpine
        restart: on-failure
    mongo:
        image: mongo:4
        restart: on-failure
#        ports:
#            - 27017:27017
    php:
        build: docker/php
        links:
            - memcached
            - mongo
        volumes:
            - ./capella:/var/www/capella
        restart: on-failure
    nginx:
        build: docker/nginx
        ports:
            - 8081:80
        links:
            - php
        volumes_from:
            - php
        restart: on-failure
